name: Build and deploy Node.js project to Azure Function App - attendance-system

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './backend'
  NODE_VERSION: '20.x'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          npm install
          npm run build --if-present
          cd ../..

      - name: List files in the backend before zipping
        run: ls -al ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

      - name: Zip backend for deployment
        run: |
          echo "Zipping the backend code..."
          cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          zip -r ../../release.zip ./*
          ls -al ../../release.zip  # Verify that the file is created
          cd ../..

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip
          retention-days: 1  # Optional: makes sure the artifact isn't expired

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ./  # Ensure artifact is downloaded to the current directory

      - name: List files after downloading artifact
        run: ls -al ./  # Check if the artifact is available

      - name: Unzip artifact
        run: unzip ./release.zip -d ./ # Unzip to the current directory

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'attendance-system'
          slot-name: 'Production'
          package: './'  # Deploy from the current directory
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6990CE976B0548079E103CFBF1F348B2 }}
